name: 🐞 버그 보고
description: 우리가 알아야 할 것을 찾았다면.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        버그 보고서를 작성하는데 시간을 내주셔서 감사합니다!

  - type: checkboxes
    attributes:
      label: 문제를 제출하기 전에 다음 질문에 담해주세요.
      options:
        - label: 문제가 재연되기 전에 서버의 버전이 업데이트 되었습니다.
          required: true
        - label: [자주묻는 질문](https://everee.gitbook.io/yujachaserver/faq/)을 확인했지만 답을 찾지 못했습니다.
          required: true
        - label: 이 문제가 이미 제기되지 않았는지 확인했습니다.
          required: true

  - type: input
    id: app_version
    attributes:
      label: 서버 버전
      description: 어떤 버전에서 오류가 발생하나요?
      placeholder: 예를 들어, 2.13.1
    validations:
      required: true

  - type: textarea
    attributes:
      label: 환경
      description: |
        Examples:
          - **OS**: Windows 11
          - **Version**: 23H2
      value: |
          - OS:
          - Device:
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: 문제 세부정보
      description: 이 문제를 재연하기 위한 단계를 알려주세요
      placeholder:
      value: |
        문제를 재연하는 방법:
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: how_it_should_be
    attributes:
      label: 예상 동작
      description:
      placeholder: 어떤 일이 일어나기를 기대하는지 명확하고 간결하게 설명해주세요.
    validations:
      required: false
  
  - type: textarea
    id: how_it_is
    attributes:
      label: 실제 행동
      placeholder: 대신 무슨 일이 일어났는지 명확하게 설명해주세요.
    validations:
      required: true

  - type: textarea
    id: screens
    attributes:
      label: Screenshots
      description: |
        문제를 설명하는 스크린샷이 있는 경우 추가하세요.
        이미지를 끌어서 놓거나 클립보드에서 붙여넣을 수 있습니다.
        `<details> </details>`태그를 사용하여 스포일러 아래에 스크린샷을 숨깁니다.
      placeholder: If applicable add screenshots explaining your problem.
      value: |
          <details><summary>Screenshot 1</summary>
          <!-- 스크린샷을 여기에 붙여넣으세요 -->
          </details>
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 추가 정보
      placeholder: 문제애 대한 추가 정보를 여기에 추가해주세요.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        [중요한 문제에](https://github.com/MadeByPP/YujachaServer/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) :+1:로 추천해주세요
