name: 🌱 Feature request
description: 어떻게 하면 유자차 서버가 개선될지 알고 있다면
labels: ["기능 요청"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: 문제 상세설명
      description: 무슨 일인가요?
      placeholder: 이 기능 요청이 버그와 관련되어 있나요? 버그가 무엇인지 명확하고 확실하게 설명해주세요.
    validations:
      required: true

  - type: textarea
    id: how_it_should_be
    attributes:
      label: 해결책 제안
      description:
      placeholder: 원하는 해결책을 명확하고 간결하게 설명해주세요.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 대체 해결책
      description:
      placeholder: 고려한 대체 해결책 또는 기능에 대한 명확하고 간결하게 설명해주세요.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        [중요한 문제에](https://github.com/AdguardTeam/AdguardForiOS/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+) :+1:로 추천해주세요
